from PyQt5 import QtWidgets, QtCore
from PyQt5.QtCore import QDateTime


class Tasks_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(693, 451)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.posts_label = QtWidgets.QLabel(Dialog)
        self.posts_label.setObjectName("posts_label")
        self.verticalLayout.addWidget(self.posts_label)
        self.posts_listWidget = QtWidgets.QListWidget(Dialog)
        self.posts_listWidget.setObjectName("posts_listWidget")
        self.verticalLayout.addWidget(self.posts_listWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.targets_label = QtWidgets.QLabel(Dialog)
        self.targets_label.setObjectName("targets_label")
        self.verticalLayout_2.addWidget(self.targets_label)
        self.targets_listWidget = QtWidgets.QListWidget(Dialog)
        self.targets_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.targets_listWidget.setSelectionRectVisible(False)
        self.targets_listWidget.setObjectName("targets_listWidget")
        self.verticalLayout_2.addWidget(self.targets_listWidget)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.date_time_label = QtWidgets.QLabel(Dialog)
        self.date_time_label.setObjectName("date_time_label")
        self.verticalLayout_3.addWidget(self.date_time_label)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(QDateTime.currentDateTime())
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setMinimumDateTime(QDateTime.currentDateTime().addSecs(60))
        self.verticalLayout_3.addWidget(self.dateTimeEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.task_name_label = QtWidgets.QLabel(Dialog)
        self.task_name_label.setObjectName("task_name_label")
        self.verticalLayout_4.addWidget(self.task_name_label)
        self.task_name_line_edit = QtWidgets.QLineEdit(Dialog)
        self.task_name_line_edit.setObjectName("task_name_line_edit")
        self.verticalLayout_4.addWidget(self.task_name_line_edit)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Task Dialog"))
        self.posts_label.setText(_translate("Dialog", "Pick a post:"))
        self.targets_label.setText(_translate("Dialog", "Pick targets:"))
        self.date_time_label.setText(_translate("Dialog", "Pick a date and time:"))
        self.task_name_label.setText(_translate("Dialog", "Task name:"))